### ISSUE TITLE
Error with python<3.9

### ISSUE THREAD

**Issue by ivo-s** [alerque/sfdnormalize#9]
The string method `removeprefix()` is only available since python 3.9, and so this line throws an error in python 3.8 and lower:
https://github.com/alerque/sfdnormalize/blob/6700307083f71588f6d65762f6aafd4e7f3190e6/sfdnormalize/__main__.py#L262
I suggest replacing the method by `[len('usage: '):]`.

**Comment by ctrlcctrlv** [comment]
That's uglier. Could just require Python 3.9+ in the manifest.

**Comment by alerque** [comment]
I agree that's ugly, but given that this is currently in active use in a couple repositories using CI runners that have older Python, it seems logical to keep supporting old versions a little bit longer. If there was a significant amount of code that needed fixing I'd say requiring new Python would be fine, but given the only current issue is running `--help`, it seems like a weak case for requiring new-ish Python.

**Comment by ivo-s** [comment]
I wrote this issue after failing to move from 3.8 to 3.9 through packages in my distro, and after interrupting Anaconda when it got stuck trying to process upgrading Python just like a Nutrimat trying to give Arthur Dent tea.

I agree that it's less nice, but it's still readable and it's a tiny change that will save some hair on people's heads :-) When I try to maintain my way of processing fonts, stuff stops working and I need to update, which breaks more stuff...and this is one less tree in the jungle.

**Comment by alerque** [comment]
@ivo-s Would you like to submit a PR or prefer I just patch it? Either way I think I'm fine with this just to grease the wheels. It's ugly but not a real maintenance burden on this end. If I (or anybody) does any significant development work on this and wants to use new language features I'd be happy to make new Python a requirement, but for this use case there isn't a clear benefit to this project or potential users to being one more tree in the jungle that needs trimming.

**Comment by ivo-s** [comment]
PR seemed too convoluted to me for this, so unless you prefer it, you can just patch it. :+1:

**Comment by alerque** [comment]
Would having a patch release for this help anybody's workflow? There aren't any other exciting changes in the pipeline that are likely to trigger a release any time soon.
